In [1]:
import numpy as np
from logistic_reg import BinaryLogisticRegression

# Applying to Dummy data

In [2]:
dummy = np.array([[1,2,3],[4,5,6],[7,8,9]])
y = np.array([0,1,1])

In [3]:
lr = BinaryLogisticRegression(dummy,y)

In [4]:
lr.fit()

In [5]:
lr.predict(dummy)

array([0., 1., 1.])

# Scikit Breast Cancer Dataset

In [6]:
from sklearn.datasets import load_breast_cancer

In [7]:
data = load_breast_cancer()

In [8]:
data['data'],data['target']

(array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
 

In [9]:
X_train,y_train = data['data'][:500],data['target'][:500]
X_test,y_test = data['data'][500:],data['target'][500:]

In [10]:
lr = BinaryLogisticRegression(X_train,y_train,no_iter = 1000, learning_rate = 0.5)
lr.fit()

F:\MLfromscratch\LinearMethods\LogisticRegression\logistic_reg.py:27: RuntimeWarning: overflow encountered in exp
  return(1/(1+np.exp(-x)))


In [20]:
prediction = lr.predict(X_test)>0.5

In [21]:
prediction>0.5,y_test>0.5

(array([False, False,  True, False,  True,  True,  True,  True,  True,
         True,  True,  True, False, False, False,  True, False, False,
        False,  True,  True, False,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True, False, False,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
        False, False, False, False, False,  True]),
 array([ True, False,  True, False,  True,  True,  True,  True,  True,
        False,  True,  True, False,  True, False,  True, False, False,
         True,  True,  True, False,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True, False,  True, False,
        False,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  Tr

In [22]:
#Accuracy for train set

sum(prediction == y_test)/69



0.8985507246376812

In [23]:
#Result of 89.8 % accuracy

In [24]:
np.array([True,True] , dtype = int)

array([1, 1])