In [158]:
import numpy as np
from logistic_reg import MultiLogisticRegression

In [159]:
dummy = np.array([[1,2,3,7],[4,2,4,6],[7,8,9,4],[1,4,3,2]])
y = np.array([0,1,1,0])

#(np.exp(dummy).T/ np.exp(dummy).sum(axis = 1)).T
(np.exp(dummy)/ np.exp(dummy).sum(axis = 1,keepdims = True))

array([[0.00241233, 0.00655741, 0.01782488, 0.97320538],
       [0.10499359, 0.01420934, 0.10499359, 0.77580349],
       [0.08962882, 0.24363641, 0.66227241, 0.00446236],
       [0.0320586 , 0.64391426, 0.23688282, 0.08714432]])

In [160]:
lr = MultiLogisticRegression(dummy,y)


In [161]:
lr.fit()

In [162]:
lr.predict(dummy)

array([[9.99999970e-01, 3.04546749e-08],
       [5.16443130e-04, 9.99483557e-01],
       [6.09380284e-06, 9.99993906e-01],
       [9.99996611e-01, 3.38882434e-06]])

In [163]:
from sklearn.datasets import load_breast_cancer

In [164]:
data = load_breast_cancer()

In [165]:
data['data'],data['target']

(array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
 

In [166]:
X_train,y_train = data['data'][:500],data['target'][:500]
X_test,y_test = data['data'][500:],data['target'][500:]

In [167]:
lr = MultiLogisticRegression(X_train,y_train,no_iter = 1000, learning_rate = 0.05)
lr.fit()

In [168]:
prediction = lr.predict(X_test)
prediction


F:\mlfromscratch\LinearMethods\LogisticRegression\logistic_reg.py:110: RuntimeWarning: overflow encountered in exp
  sumer = exponential.sum(axis = 1,keepdims = True)
F:\mlfromscratch\LinearMethods\LogisticRegression\logistic_reg.py:112: RuntimeWarning: invalid value encountered in true_divide
  #return (exponential.T/sumer).T


array([[2.11525337e-053, 1.00000000e+000],
       [8.68872630e-014, 1.00000000e+000],
       [1.05678530e-112, 1.00000000e+000],
       [            nan, 0.00000000e+000],
       [4.68891893e-087, 1.00000000e+000],
       [2.15471318e-088, 1.00000000e+000],
       [1.35882610e-127, 1.00000000e+000],
       [6.02470920e-124, 1.00000000e+000],
       [7.83544338e-139, 1.00000000e+000],
       [7.16434401e-064, 1.00000000e+000],
       [5.10744688e-132, 1.00000000e+000],
       [1.08215090e-145, 1.00000000e+000],
       [1.00000000e+000, 2.10798504e-095],
       [1.29110317e-002, 9.87088968e-001],
       [1.00000000e+000, 6.04356353e-055],
       [1.01536408e-079, 1.00000000e+000],
       [1.00000000e+000, 1.65970137e-196],
       [1.00000000e+000, 7.78233907e-147],
       [2.26277032e-003, 9.97737230e-001],
       [1.36078360e-055, 1.00000000e+000],
       [5.38869436e-066, 1.00000000e+000],
       [1.00000000e+000, 0.00000000e+000],
       [1.76326120e-125, 1.00000000e+000],
       [1.0

In [169]:
y_bool = y_test>0.5

In [170]:
p = prediction[:,1]>0.5

In [171]:
sum(p == y_bool)/len(p)

0.927536231884058