In [1]:
import numpy as np
from lda import LDA


# Applying to Dummy data

In [11]:
dummy = np.array([[1,2,3,7],[4,2,4,6],[7,8,9,4],[1,4,3,2]])
y = np.array([0,1,1,0])


In [12]:
lda = LDA(dummy,y)

In [13]:
lda.fit()

In [18]:
for i in range(len(dummy)):
    l = lda.predict(np.array([dummy[i]]))
    print(l)

[0.]
[1.]
[1.]
[0.]


# Scikit Breast Cancer Dataset

In [19]:
from sklearn.datasets import load_breast_cancer

In [20]:
data = load_breast_cancer()

In [21]:
data['data'],data['target']

(array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
 

In [22]:
X_train,y_train = data['data'][:500],data['target'][:500]
X_test,y_test = data['data'][500:],data['target'][500:]

In [24]:
lda = LDA(X_train,y_train)
lda.fit()

In [25]:
prediction = lda.predict(X_test)>0.5

In [26]:
prediction>0.5,y_test>0.5

(array([ True, False,  True, False,  True,  True,  True,  True,  True,
        False,  True,  True, False,  True,  True,  True, False, False,
         True,  True,  True, False,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True, False,  True, False,
         True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True, False,
        False, False, False, False, False,  True]),
 array([ True, False,  True, False,  True,  True,  True,  True,  True,
        False,  True,  True, False,  True, False,  True, False, False,
         True,  True,  True, False,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True, False,  True, False,
        False,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  Tr

In [30]:
sum(prediction == y_test)/len(prediction)

0.9565217391304348

In [28]:
np.array([True,True] , dtype = int)

array([1, 1])